// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: control_plane.proto

package controlplane

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeState int32

const (
	NodeState_NODE_STATE_UNKNOWN   NodeState = 0
	NodeState_NODE_STATE_ALIVE     NodeState = 1
	NodeState_NODE_STATE_SUSPECT   NodeState = 2
	NodeState_NODE_STATE_DOWN      NodeState = 3
	NodeState_NODE_STATE_TOMBSTONE NodeState = 4
)

// Enum value maps for NodeState.
var (
	NodeState_name = map[int32]string{
		0: "NODE_STATE_UNKNOWN",
		1: "NODE_STATE_ALIVE",
		2: "NODE_STATE_SUSPECT",
		3: "NODE_STATE_DOWN",
		4: "NODE_STATE_TOMBSTONE",
	}
	NodeState_value = map[string]int32{
		"NODE_STATE_UNKNOWN":   0,
		"NODE_STATE_ALIVE":     1,
		"NODE_STATE_SUSPECT":   2,
		"NODE_STATE_DOWN":      3,
		"NODE_STATE_TOMBSTONE": 4,
	}
)

func (x NodeState) Enum() *NodeState {
	p := new(NodeState)
	*p = x
	return p
}

func (x NodeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeState) Descriptor() protoreflect.EnumDescriptor {
	return file_control_plane_proto_enumTypes[0].Descriptor()
}

func (NodeState) Type() protoreflect.EnumType {
	return &file_control_plane_proto_enumTypes[0]
}

func (x NodeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeState.Descriptor instead.
func (NodeState) EnumDescriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{0}
}

type StorageTier int32

const (
	StorageTier_STORAGE_TIER_UNKNOWN StorageTier = 0
	StorageTier_STORAGE_TIER_MEMORY  StorageTier = 1
	StorageTier_STORAGE_TIER_DISK    StorageTier = 2
)

// Enum value maps for StorageTier.
var (
	StorageTier_name = map[int32]string{
		0: "STORAGE_TIER_UNKNOWN",
		1: "STORAGE_TIER_MEMORY",
		2: "STORAGE_TIER_DISK",
	}
	StorageTier_value = map[string]int32{
		"STORAGE_TIER_UNKNOWN": 0,
		"STORAGE_TIER_MEMORY":  1,
		"STORAGE_TIER_DISK":    2,
	}
)

func (x StorageTier) Enum() *StorageTier {
	p := new(StorageTier)
	*p = x
	return p
}

func (x StorageTier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StorageTier) Descriptor() protoreflect.EnumDescriptor {
	return file_control_plane_proto_enumTypes[1].Descriptor()
}

func (StorageTier) Type() protoreflect.EnumType {
	return &file_control_plane_proto_enumTypes[1]
}

func (x StorageTier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StorageTier.Descriptor instead.
func (StorageTier) EnumDescriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{1}
}

type Node struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr                  string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	State                 NodeState              `protobuf:"varint,3,opt,name=state,proto3,enum=kvcache.controlplane.v1.NodeState" json:"state,omitempty"`
	Version               uint64                 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	LastHeartbeatUnixNano int64                  `protobuf:"varint,5,opt,name=last_heartbeat_unix_nano,json=lastHeartbeatUnixNano,proto3" json:"last_heartbeat_unix_nano,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_control_plane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Node) GetState() NodeState {
	if x != nil {
		return x.State
	}
	return NodeState_NODE_STATE_UNKNOWN
}

func (x *Node) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Node) GetLastHeartbeatUnixNano() int64 {
	if x != nil {
		return x.LastHeartbeatUnixNano
	}
	return 0
}

type BlockMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockId       uint64                 `protobuf:"varint,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	Length        uint64                 `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	Checksum      uint32                 `protobuf:"varint,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Generation    uint64                 `protobuf:"varint,4,opt,name=generation,proto3" json:"generation,omitempty"`
	Seq           uint64                 `protobuf:"varint,5,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockMeta) Reset() {
	*x = BlockMeta{}
	mi := &file_control_plane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockMeta) ProtoMessage() {}

func (x *BlockMeta) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockMeta.ProtoReflect.Descriptor instead.
func (*BlockMeta) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{1}
}

func (x *BlockMeta) GetBlockId() uint64 {
	if x != nil {
		return x.BlockId
	}
	return 0
}

func (x *BlockMeta) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *BlockMeta) GetChecksum() uint32 {
	if x != nil {
		return x.Checksum
	}
	return 0
}

func (x *BlockMeta) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *BlockMeta) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type BlockLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockId       uint64                 `protobuf:"varint,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Addr          string                 `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
	Tier          StorageTier            `protobuf:"varint,4,opt,name=tier,proto3,enum=kvcache.controlplane.v1.StorageTier" json:"tier,omitempty"`
	Meta          *BlockMeta             `protobuf:"bytes,5,opt,name=meta,proto3" json:"meta,omitempty"`
	Version       uint64                 `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockLocation) Reset() {
	*x = BlockLocation{}
	mi := &file_control_plane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockLocation) ProtoMessage() {}

func (x *BlockLocation) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockLocation.ProtoReflect.Descriptor instead.
func (*BlockLocation) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{2}
}

func (x *BlockLocation) GetBlockId() uint64 {
	if x != nil {
		return x.BlockId
	}
	return 0
}

func (x *BlockLocation) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *BlockLocation) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *BlockLocation) GetTier() StorageTier {
	if x != nil {
		return x.Tier
	}
	return StorageTier_STORAGE_TIER_UNKNOWN
}

func (x *BlockLocation) GetMeta() *BlockMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *BlockLocation) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type RegisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *Node                  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_control_plane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterNodeRequest) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type RegisterNodeResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Self              *Node                  `protobuf:"bytes,1,opt,name=self,proto3" json:"self,omitempty"`
	MembershipVersion uint64                 `protobuf:"varint,2,opt,name=membership_version,json=membershipVersion,proto3" json:"membership_version,omitempty"`
	RouteVersion      uint64                 `protobuf:"varint,3,opt,name=route_version,json=routeVersion,proto3" json:"route_version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_control_plane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterNodeResponse) GetSelf() *Node {
	if x != nil {
		return x.Self
	}
	return nil
}

func (x *RegisterNodeResponse) GetMembershipVersion() uint64 {
	if x != nil {
		return x.MembershipVersion
	}
	return 0
}

func (x *RegisterNodeResponse) GetRouteVersion() uint64 {
	if x != nil {
		return x.RouteVersion
	}
	return 0
}

type HeartbeatRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	HeartbeatUnixNano int64                  `protobuf:"varint,2,opt,name=heartbeat_unix_nano,json=heartbeatUnixNano,proto3" json:"heartbeat_unix_nano,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_control_plane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetHeartbeatUnixNano() int64 {
	if x != nil {
		return x.HeartbeatUnixNano
	}
	return 0
}

type HeartbeatResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Node              *Node                  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	MembershipVersion uint64                 `protobuf:"varint,2,opt,name=membership_version,json=membershipVersion,proto3" json:"membership_version,omitempty"`
	RouteVersion      uint64                 `protobuf:"varint,3,opt,name=route_version,json=routeVersion,proto3" json:"route_version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_control_plane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *HeartbeatResponse) GetMembershipVersion() uint64 {
	if x != nil {
		return x.MembershipVersion
	}
	return 0
}

func (x *HeartbeatResponse) GetRouteVersion() uint64 {
	if x != nil {
		return x.RouteVersion
	}
	return 0
}

type LeaveNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveNodeRequest) Reset() {
	*x = LeaveNodeRequest{}
	mi := &file_control_plane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveNodeRequest) ProtoMessage() {}

func (x *LeaveNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveNodeRequest.ProtoReflect.Descriptor instead.
func (*LeaveNodeRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{7}
}

func (x *LeaveNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *LeaveNodeRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type LeaveNodeResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Tombstone         *Node                  `protobuf:"bytes,1,opt,name=tombstone,proto3" json:"tombstone,omitempty"`
	MembershipVersion uint64                 `protobuf:"varint,2,opt,name=membership_version,json=membershipVersion,proto3" json:"membership_version,omitempty"`
	RouteVersion      uint64                 `protobuf:"varint,3,opt,name=route_version,json=routeVersion,proto3" json:"route_version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LeaveNodeResponse) Reset() {
	*x = LeaveNodeResponse{}
	mi := &file_control_plane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveNodeResponse) ProtoMessage() {}

func (x *LeaveNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveNodeResponse.ProtoReflect.Descriptor instead.
func (*LeaveNodeResponse) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{8}
}

func (x *LeaveNodeResponse) GetTombstone() *Node {
	if x != nil {
		return x.Tombstone
	}
	return nil
}

func (x *LeaveNodeResponse) GetMembershipVersion() uint64 {
	if x != nil {
		return x.MembershipVersion
	}
	return 0
}

func (x *LeaveNodeResponse) GetRouteVersion() uint64 {
	if x != nil {
		return x.RouteVersion
	}
	return 0
}

type GetMembershipRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// known_membership_version 允许服务端未来做增量返回；当前 MVP 可忽略并返回全量。
	KnownMembershipVersion uint64 `protobuf:"varint,1,opt,name=known_membership_version,json=knownMembershipVersion,proto3" json:"known_membership_version,omitempty"`
	IncludeTombstones      bool   `protobuf:"varint,2,opt,name=include_tombstones,json=includeTombstones,proto3" json:"include_tombstones,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetMembershipRequest) Reset() {
	*x = GetMembershipRequest{}
	mi := &file_control_plane_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembershipRequest) ProtoMessage() {}

func (x *GetMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembershipRequest.ProtoReflect.Descriptor instead.
func (*GetMembershipRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{9}
}

func (x *GetMembershipRequest) GetKnownMembershipVersion() uint64 {
	if x != nil {
		return x.KnownMembershipVersion
	}
	return 0
}

func (x *GetMembershipRequest) GetIncludeTombstones() bool {
	if x != nil {
		return x.IncludeTombstones
	}
	return false
}

type GetMembershipResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Nodes             []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	MembershipVersion uint64                 `protobuf:"varint,2,opt,name=membership_version,json=membershipVersion,proto3" json:"membership_version,omitempty"`
	RouteVersion      uint64                 `protobuf:"varint,3,opt,name=route_version,json=routeVersion,proto3" json:"route_version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetMembershipResponse) Reset() {
	*x = GetMembershipResponse{}
	mi := &file_control_plane_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMembershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembershipResponse) ProtoMessage() {}

func (x *GetMembershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembershipResponse.ProtoReflect.Descriptor instead.
func (*GetMembershipResponse) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{10}
}

func (x *GetMembershipResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *GetMembershipResponse) GetMembershipVersion() uint64 {
	if x != nil {
		return x.MembershipVersion
	}
	return 0
}

func (x *GetMembershipResponse) GetRouteVersion() uint64 {
	if x != nil {
		return x.RouteVersion
	}
	return 0
}

type SyncMembershipRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Nodes             []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	MembershipVersion uint64                 `protobuf:"varint,2,opt,name=membership_version,json=membershipVersion,proto3" json:"membership_version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SyncMembershipRequest) Reset() {
	*x = SyncMembershipRequest{}
	mi := &file_control_plane_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMembershipRequest) ProtoMessage() {}

func (x *SyncMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMembershipRequest.ProtoReflect.Descriptor instead.
func (*SyncMembershipRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{11}
}

func (x *SyncMembershipRequest) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *SyncMembershipRequest) GetMembershipVersion() uint64 {
	if x != nil {
		return x.MembershipVersion
	}
	return 0
}

type SyncMembershipResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Nodes             []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	MembershipVersion uint64                 `protobuf:"varint,2,opt,name=membership_version,json=membershipVersion,proto3" json:"membership_version,omitempty"`
	RouteVersion      uint64                 `protobuf:"varint,3,opt,name=route_version,json=routeVersion,proto3" json:"route_version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SyncMembershipResponse) Reset() {
	*x = SyncMembershipResponse{}
	mi := &file_control_plane_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncMembershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMembershipResponse) ProtoMessage() {}

func (x *SyncMembershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMembershipResponse.ProtoReflect.Descriptor instead.
func (*SyncMembershipResponse) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{12}
}

func (x *SyncMembershipResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *SyncMembershipResponse) GetMembershipVersion() uint64 {
	if x != nil {
		return x.MembershipVersion
	}
	return 0
}

func (x *SyncMembershipResponse) GetRouteVersion() uint64 {
	if x != nil {
		return x.RouteVersion
	}
	return 0
}

type RouteBlockRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	BlockId uint64                 `protobuf:"varint,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	// candidates 表示需要返回的物理节点数量，包含 primary。
	// 服务端应把 0 降级为 1。
	Candidates    uint32 `protobuf:"varint,2,opt,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteBlockRequest) Reset() {
	*x = RouteBlockRequest{}
	mi := &file_control_plane_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteBlockRequest) ProtoMessage() {}

func (x *RouteBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteBlockRequest.ProtoReflect.Descriptor instead.
func (*RouteBlockRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{13}
}

func (x *RouteBlockRequest) GetBlockId() uint64 {
	if x != nil {
		return x.BlockId
	}
	return 0
}

func (x *RouteBlockRequest) GetCandidates() uint32 {
	if x != nil {
		return x.Candidates
	}
	return 0
}

type RouteBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockId       uint64                 `protobuf:"varint,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	Primary       *Node                  `protobuf:"bytes,2,opt,name=primary,proto3" json:"primary,omitempty"`
	Candidates    []*Node                `protobuf:"bytes,3,rep,name=candidates,proto3" json:"candidates,omitempty"`
	RouteVersion  uint64                 `protobuf:"varint,4,opt,name=route_version,json=routeVersion,proto3" json:"route_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteBlockResponse) Reset() {
	*x = RouteBlockResponse{}
	mi := &file_control_plane_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteBlockResponse) ProtoMessage() {}

func (x *RouteBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteBlockResponse.ProtoReflect.Descriptor instead.
func (*RouteBlockResponse) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{14}
}

func (x *RouteBlockResponse) GetBlockId() uint64 {
	if x != nil {
		return x.BlockId
	}
	return 0
}

func (x *RouteBlockResponse) GetPrimary() *Node {
	if x != nil {
		return x.Primary
	}
	return nil
}

func (x *RouteBlockResponse) GetCandidates() []*Node {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *RouteBlockResponse) GetRouteVersion() uint64 {
	if x != nil {
		return x.RouteVersion
	}
	return 0
}

type AnnounceBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Meta          *BlockMeta             `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Tier          StorageTier            `protobuf:"varint,3,opt,name=tier,proto3,enum=kvcache.controlplane.v1.StorageTier" json:"tier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnounceBlockRequest) Reset() {
	*x = AnnounceBlockRequest{}
	mi := &file_control_plane_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnounceBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnounceBlockRequest) ProtoMessage() {}

func (x *AnnounceBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnounceBlockRequest.ProtoReflect.Descriptor instead.
func (*AnnounceBlockRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{15}
}

func (x *AnnounceBlockRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AnnounceBlockRequest) GetMeta() *BlockMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *AnnounceBlockRequest) GetTier() StorageTier {
	if x != nil {
		return x.Tier
	}
	return StorageTier_STORAGE_TIER_UNKNOWN
}

type AnnounceBlockResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Location        *BlockLocation         `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	LocationVersion uint64                 `protobuf:"varint,2,opt,name=location_version,json=locationVersion,proto3" json:"location_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AnnounceBlockResponse) Reset() {
	*x = AnnounceBlockResponse{}
	mi := &file_control_plane_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnounceBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnounceBlockResponse) ProtoMessage() {}

func (x *AnnounceBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnounceBlockResponse.ProtoReflect.Descriptor instead.
func (*AnnounceBlockResponse) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{16}
}

func (x *AnnounceBlockResponse) GetLocation() *BlockLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *AnnounceBlockResponse) GetLocationVersion() uint64 {
	if x != nil {
		return x.LocationVersion
	}
	return 0
}

type ForgetBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	BlockId       uint64                 `protobuf:"varint,2,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	Tier          StorageTier            `protobuf:"varint,3,opt,name=tier,proto3,enum=kvcache.controlplane.v1.StorageTier" json:"tier,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgetBlockRequest) Reset() {
	*x = ForgetBlockRequest{}
	mi := &file_control_plane_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgetBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgetBlockRequest) ProtoMessage() {}

func (x *ForgetBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgetBlockRequest.ProtoReflect.Descriptor instead.
func (*ForgetBlockRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{17}
}

func (x *ForgetBlockRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ForgetBlockRequest) GetBlockId() uint64 {
	if x != nil {
		return x.BlockId
	}
	return 0
}

func (x *ForgetBlockRequest) GetTier() StorageTier {
	if x != nil {
		return x.Tier
	}
	return StorageTier_STORAGE_TIER_UNKNOWN
}

func (x *ForgetBlockRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ForgetBlockResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BlockId         uint64                 `protobuf:"varint,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	NodeId          string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	LocationVersion uint64                 `protobuf:"varint,3,opt,name=location_version,json=locationVersion,proto3" json:"location_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ForgetBlockResponse) Reset() {
	*x = ForgetBlockResponse{}
	mi := &file_control_plane_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgetBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgetBlockResponse) ProtoMessage() {}

func (x *ForgetBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgetBlockResponse.ProtoReflect.Descriptor instead.
func (*ForgetBlockResponse) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{18}
}

func (x *ForgetBlockResponse) GetBlockId() uint64 {
	if x != nil {
		return x.BlockId
	}
	return 0
}

func (x *ForgetBlockResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ForgetBlockResponse) GetLocationVersion() uint64 {
	if x != nil {
		return x.LocationVersion
	}
	return 0
}

type GetBlockLocationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockId       uint64                 `protobuf:"varint,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockLocationsRequest) Reset() {
	*x = GetBlockLocationsRequest{}
	mi := &file_control_plane_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockLocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockLocationsRequest) ProtoMessage() {}

func (x *GetBlockLocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockLocationsRequest.ProtoReflect.Descriptor instead.
func (*GetBlockLocationsRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{19}
}

func (x *GetBlockLocationsRequest) GetBlockId() uint64 {
	if x != nil {
		return x.BlockId
	}
	return 0
}

type GetBlockLocationsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BlockId         uint64                 `protobuf:"varint,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	Locations       []*BlockLocation       `protobuf:"bytes,2,rep,name=locations,proto3" json:"locations,omitempty"`
	LocationVersion uint64                 `protobuf:"varint,3,opt,name=location_version,json=locationVersion,proto3" json:"location_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetBlockLocationsResponse) Reset() {
	*x = GetBlockLocationsResponse{}
	mi := &file_control_plane_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockLocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockLocationsResponse) ProtoMessage() {}

func (x *GetBlockLocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockLocationsResponse.ProtoReflect.Descriptor instead.
func (*GetBlockLocationsResponse) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{20}
}

func (x *GetBlockLocationsResponse) GetBlockId() uint64 {
	if x != nil {
		return x.BlockId
	}
	return 0
}

func (x *GetBlockLocationsResponse) GetLocations() []*BlockLocation {
	if x != nil {
		return x.Locations
	}
	return nil
}

func (x *GetBlockLocationsResponse) GetLocationVersion() uint64 {
	if x != nil {
		return x.LocationVersion
	}
	return 0
}

var File_control_plane_proto protoreflect.FileDescriptor

const file_control_plane_proto_rawDesc = "" +
	"\n" +
	"\x13control_plane.proto\x12\x17kvcache.controlplane.v1\"\xb7\x01\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x128\n" +
	"\x05state\x18\x03 \x01(\x0e2\".kvcache.controlplane.v1.NodeStateR\x05state\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x04R\aversion\x127\n" +
	"\x18last_heartbeat_unix_nano\x18\x05 \x01(\x03R\x15lastHeartbeatUnixNano\"\x8c\x01\n" +
	"\tBlockMeta\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\x04R\ablockId\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x04R\x06length\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\rR\bchecksum\x12\x1e\n" +
	"\n" +
	"generation\x18\x04 \x01(\x04R\n" +
	"generation\x12\x10\n" +
	"\x03seq\x18\x05 \x01(\x04R\x03seq\"\xe3\x01\n" +
	"\rBlockLocation\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\x04R\ablockId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04addr\x18\x03 \x01(\tR\x04addr\x128\n" +
	"\x04tier\x18\x04 \x01(\x0e2$.kvcache.controlplane.v1.StorageTierR\x04tier\x126\n" +
	"\x04meta\x18\x05 \x01(\v2\".kvcache.controlplane.v1.BlockMetaR\x04meta\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x04R\aversion\"H\n" +
	"\x13RegisterNodeRequest\x121\n" +
	"\x04node\x18\x01 \x01(\v2\x1d.kvcache.controlplane.v1.NodeR\x04node\"\x9d\x01\n" +
	"\x14RegisterNodeResponse\x121\n" +
	"\x04self\x18\x01 \x01(\v2\x1d.kvcache.controlplane.v1.NodeR\x04self\x12-\n" +
	"\x12membership_version\x18\x02 \x01(\x04R\x11membershipVersion\x12#\n" +
	"\rroute_version\x18\x03 \x01(\x04R\frouteVersion\"[\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12.\n" +
	"\x13heartbeat_unix_nano\x18\x02 \x01(\x03R\x11heartbeatUnixNano\"\x9a\x01\n" +
	"\x11HeartbeatResponse\x121\n" +
	"\x04node\x18\x01 \x01(\v2\x1d.kvcache.controlplane.v1.NodeR\x04node\x12-\n" +
	"\x12membership_version\x18\x02 \x01(\x04R\x11membershipVersion\x12#\n" +
	"\rroute_version\x18\x03 \x01(\x04R\frouteVersion\"C\n" +
	"\x10LeaveNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xa4\x01\n" +
	"\x11LeaveNodeResponse\x12;\n" +
	"\ttombstone\x18\x01 \x01(\v2\x1d.kvcache.controlplane.v1.NodeR\ttombstone\x12-\n" +
	"\x12membership_version\x18\x02 \x01(\x04R\x11membershipVersion\x12#\n" +
	"\rroute_version\x18\x03 \x01(\x04R\frouteVersion\"\x7f\n" +
	"\x14GetMembershipRequest\x128\n" +
	"\x18known_membership_version\x18\x01 \x01(\x04R\x16knownMembershipVersion\x12-\n" +
	"\x12include_tombstones\x18\x02 \x01(\bR\x11includeTombstones\"\xa0\x01\n" +
	"\x15GetMembershipResponse\x123\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1d.kvcache.controlplane.v1.NodeR\x05nodes\x12-\n" +
	"\x12membership_version\x18\x02 \x01(\x04R\x11membershipVersion\x12#\n" +
	"\rroute_version\x18\x03 \x01(\x04R\frouteVersion\"{\n" +
	"\x15SyncMembershipRequest\x123\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1d.kvcache.controlplane.v1.NodeR\x05nodes\x12-\n" +
	"\x12membership_version\x18\x02 \x01(\x04R\x11membershipVersion\"\xa1\x01\n" +
	"\x16SyncMembershipResponse\x123\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1d.kvcache.controlplane.v1.NodeR\x05nodes\x12-\n" +
	"\x12membership_version\x18\x02 \x01(\x04R\x11membershipVersion\x12#\n" +
	"\rroute_version\x18\x03 \x01(\x04R\frouteVersion\"N\n" +
	"\x11RouteBlockRequest\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\x04R\ablockId\x12\x1e\n" +
	"\n" +
	"candidates\x18\x02 \x01(\rR\n" +
	"candidates\"\xcc\x01\n" +
	"\x12RouteBlockResponse\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\x04R\ablockId\x127\n" +
	"\aprimary\x18\x02 \x01(\v2\x1d.kvcache.controlplane.v1.NodeR\aprimary\x12=\n" +
	"\n" +
	"candidates\x18\x03 \x03(\v2\x1d.kvcache.controlplane.v1.NodeR\n" +
	"candidates\x12#\n" +
	"\rroute_version\x18\x04 \x01(\x04R\frouteVersion\"\xa1\x01\n" +
	"\x14AnnounceBlockRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x126\n" +
	"\x04meta\x18\x02 \x01(\v2\".kvcache.controlplane.v1.BlockMetaR\x04meta\x128\n" +
	"\x04tier\x18\x03 \x01(\x0e2$.kvcache.controlplane.v1.StorageTierR\x04tier\"\x86\x01\n" +
	"\x15AnnounceBlockResponse\x12B\n" +
	"\blocation\x18\x01 \x01(\v2&.kvcache.controlplane.v1.BlockLocationR\blocation\x12)\n" +
	"\x10location_version\x18\x02 \x01(\x04R\x0flocationVersion\"\x9a\x01\n" +
	"\x12ForgetBlockRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x19\n" +
	"\bblock_id\x18\x02 \x01(\x04R\ablockId\x128\n" +
	"\x04tier\x18\x03 \x01(\x0e2$.kvcache.controlplane.v1.StorageTierR\x04tier\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"t\n" +
	"\x13ForgetBlockResponse\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\x04R\ablockId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12)\n" +
	"\x10location_version\x18\x03 \x01(\x04R\x0flocationVersion\"5\n" +
	"\x18GetBlockLocationsRequest\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\x04R\ablockId\"\xa7\x01\n" +
	"\x19GetBlockLocationsResponse\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\x04R\ablockId\x12D\n" +
	"\tlocations\x18\x02 \x03(\v2&.kvcache.controlplane.v1.BlockLocationR\tlocations\x12)\n" +
	"\x10location_version\x18\x03 \x01(\x04R\x0flocationVersion*\x80\x01\n" +
	"\tNodeState\x12\x16\n" +
	"\x12NODE_STATE_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10NODE_STATE_ALIVE\x10\x01\x12\x16\n" +
	"\x12NODE_STATE_SUSPECT\x10\x02\x12\x13\n" +
	"\x0fNODE_STATE_DOWN\x10\x03\x12\x18\n" +
	"\x14NODE_STATE_TOMBSTONE\x10\x04*W\n" +
	"\vStorageTier\x12\x18\n" +
	"\x14STORAGE_TIER_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13STORAGE_TIER_MEMORY\x10\x01\x12\x15\n" +
	"\x11STORAGE_TIER_DISK\x10\x022\xe3\a\n" +
	"\fControlPlane\x12k\n" +
	"\fRegisterNode\x12,.kvcache.controlplane.v1.RegisterNodeRequest\x1a-.kvcache.controlplane.v1.RegisterNodeResponse\x12b\n" +
	"\tHeartbeat\x12).kvcache.controlplane.v1.HeartbeatRequest\x1a*.kvcache.controlplane.v1.HeartbeatResponse\x12b\n" +
	"\tLeaveNode\x12).kvcache.controlplane.v1.LeaveNodeRequest\x1a*.kvcache.controlplane.v1.LeaveNodeResponse\x12n\n" +
	"\rGetMembership\x12-.kvcache.controlplane.v1.GetMembershipRequest\x1a..kvcache.controlplane.v1.GetMembershipResponse\x12q\n" +
	"\x0eSyncMembership\x12..kvcache.controlplane.v1.SyncMembershipRequest\x1a/.kvcache.controlplane.v1.SyncMembershipResponse\x12e\n" +
	"\n" +
	"RouteBlock\x12*.kvcache.controlplane.v1.RouteBlockRequest\x1a+.kvcache.controlplane.v1.RouteBlockResponse\x12n\n" +
	"\rAnnounceBlock\x12-.kvcache.controlplane.v1.AnnounceBlockRequest\x1a..kvcache.controlplane.v1.AnnounceBlockResponse\x12h\n" +
	"\vForgetBlock\x12+.kvcache.controlplane.v1.ForgetBlockRequest\x1a,.kvcache.controlplane.v1.ForgetBlockResponse\x12z\n" +
	"\x11GetBlockLocations\x121.kvcache.controlplane.v1.GetBlockLocationsRequest\x1a2.kvcache.controlplane.v1.GetBlockLocationsResponseB\x10Z\x0e./controlplaneb\x06proto3"

var (
	file_control_plane_proto_rawDescOnce sync.Once
	file_control_plane_proto_rawDescData []byte
)

func file_control_plane_proto_rawDescGZIP() []byte {
	file_control_plane_proto_rawDescOnce.Do(func() {
		file_control_plane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_plane_proto_rawDesc), len(file_control_plane_proto_rawDesc)))
	})
	return file_control_plane_proto_rawDescData
}

var file_control_plane_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_control_plane_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_control_plane_proto_goTypes = []any{
	(NodeState)(0),                    // 0: kvcache.controlplane.v1.NodeState
	(StorageTier)(0),                  // 1: kvcache.controlplane.v1.StorageTier
	(*Node)(nil),                      // 2: kvcache.controlplane.v1.Node
	(*BlockMeta)(nil),                 // 3: kvcache.controlplane.v1.BlockMeta
	(*BlockLocation)(nil),             // 4: kvcache.controlplane.v1.BlockLocation
	(*RegisterNodeRequest)(nil),       // 5: kvcache.controlplane.v1.RegisterNodeRequest
	(*RegisterNodeResponse)(nil),      // 6: kvcache.controlplane.v1.RegisterNodeResponse
	(*HeartbeatRequest)(nil),          // 7: kvcache.controlplane.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),         // 8: kvcache.controlplane.v1.HeartbeatResponse
	(*LeaveNodeRequest)(nil),          // 9: kvcache.controlplane.v1.LeaveNodeRequest
	(*LeaveNodeResponse)(nil),         // 10: kvcache.controlplane.v1.LeaveNodeResponse
	(*GetMembershipRequest)(nil),      // 11: kvcache.controlplane.v1.GetMembershipRequest
	(*GetMembershipResponse)(nil),     // 12: kvcache.controlplane.v1.GetMembershipResponse
	(*SyncMembershipRequest)(nil),     // 13: kvcache.controlplane.v1.SyncMembershipRequest
	(*SyncMembershipResponse)(nil),    // 14: kvcache.controlplane.v1.SyncMembershipResponse
	(*RouteBlockRequest)(nil),         // 15: kvcache.controlplane.v1.RouteBlockRequest
	(*RouteBlockResponse)(nil),        // 16: kvcache.controlplane.v1.RouteBlockResponse
	(*AnnounceBlockRequest)(nil),      // 17: kvcache.controlplane.v1.AnnounceBlockRequest
	(*AnnounceBlockResponse)(nil),     // 18: kvcache.controlplane.v1.AnnounceBlockResponse
	(*ForgetBlockRequest)(nil),        // 19: kvcache.controlplane.v1.ForgetBlockRequest
	(*ForgetBlockResponse)(nil),       // 20: kvcache.controlplane.v1.ForgetBlockResponse
	(*GetBlockLocationsRequest)(nil),  // 21: kvcache.controlplane.v1.GetBlockLocationsRequest
	(*GetBlockLocationsResponse)(nil), // 22: kvcache.controlplane.v1.GetBlockLocationsResponse
}
var file_control_plane_proto_depIdxs = []int32{
	0,  // 0: kvcache.controlplane.v1.Node.state:type_name -> kvcache.controlplane.v1.NodeState
	1,  // 1: kvcache.controlplane.v1.BlockLocation.tier:type_name -> kvcache.controlplane.v1.StorageTier
	3,  // 2: kvcache.controlplane.v1.BlockLocation.meta:type_name -> kvcache.controlplane.v1.BlockMeta
	2,  // 3: kvcache.controlplane.v1.RegisterNodeRequest.node:type_name -> kvcache.controlplane.v1.Node
	2,  // 4: kvcache.controlplane.v1.RegisterNodeResponse.self:type_name -> kvcache.controlplane.v1.Node
	2,  // 5: kvcache.controlplane.v1.HeartbeatResponse.node:type_name -> kvcache.controlplane.v1.Node
	2,  // 6: kvcache.controlplane.v1.LeaveNodeResponse.tombstone:type_name -> kvcache.controlplane.v1.Node
	2,  // 7: kvcache.controlplane.v1.GetMembershipResponse.nodes:type_name -> kvcache.controlplane.v1.Node
	2,  // 8: kvcache.controlplane.v1.SyncMembershipRequest.nodes:type_name -> kvcache.controlplane.v1.Node
	2,  // 9: kvcache.controlplane.v1.SyncMembershipResponse.nodes:type_name -> kvcache.controlplane.v1.Node
	2,  // 10: kvcache.controlplane.v1.RouteBlockResponse.primary:type_name -> kvcache.controlplane.v1.Node
	2,  // 11: kvcache.controlplane.v1.RouteBlockResponse.candidates:type_name -> kvcache.controlplane.v1.Node
	3,  // 12: kvcache.controlplane.v1.AnnounceBlockRequest.meta:type_name -> kvcache.controlplane.v1.BlockMeta
	1,  // 13: kvcache.controlplane.v1.AnnounceBlockRequest.tier:type_name -> kvcache.controlplane.v1.StorageTier
	4,  // 14: kvcache.controlplane.v1.AnnounceBlockResponse.location:type_name -> kvcache.controlplane.v1.BlockLocation
	1,  // 15: kvcache.controlplane.v1.ForgetBlockRequest.tier:type_name -> kvcache.controlplane.v1.StorageTier
	4,  // 16: kvcache.controlplane.v1.GetBlockLocationsResponse.locations:type_name -> kvcache.controlplane.v1.BlockLocation
	5,  // 17: kvcache.controlplane.v1.ControlPlane.RegisterNode:input_type -> kvcache.controlplane.v1.RegisterNodeRequest
	7,  // 18: kvcache.controlplane.v1.ControlPlane.Heartbeat:input_type -> kvcache.controlplane.v1.HeartbeatRequest
	9,  // 19: kvcache.controlplane.v1.ControlPlane.LeaveNode:input_type -> kvcache.controlplane.v1.LeaveNodeRequest
	11, // 20: kvcache.controlplane.v1.ControlPlane.GetMembership:input_type -> kvcache.controlplane.v1.GetMembershipRequest
	13, // 21: kvcache.controlplane.v1.ControlPlane.SyncMembership:input_type -> kvcache.controlplane.v1.SyncMembershipRequest
	15, // 22: kvcache.controlplane.v1.ControlPlane.RouteBlock:input_type -> kvcache.controlplane.v1.RouteBlockRequest
	17, // 23: kvcache.controlplane.v1.ControlPlane.AnnounceBlock:input_type -> kvcache.controlplane.v1.AnnounceBlockRequest
	19, // 24: kvcache.controlplane.v1.ControlPlane.ForgetBlock:input_type -> kvcache.controlplane.v1.ForgetBlockRequest
	21, // 25: kvcache.controlplane.v1.ControlPlane.GetBlockLocations:input_type -> kvcache.controlplane.v1.GetBlockLocationsRequest
	6,  // 26: kvcache.controlplane.v1.ControlPlane.RegisterNode:output_type -> kvcache.controlplane.v1.RegisterNodeResponse
	8,  // 27: kvcache.controlplane.v1.ControlPlane.Heartbeat:output_type -> kvcache.controlplane.v1.HeartbeatResponse
	10, // 28: kvcache.controlplane.v1.ControlPlane.LeaveNode:output_type -> kvcache.controlplane.v1.LeaveNodeResponse
	12, // 29: kvcache.controlplane.v1.ControlPlane.GetMembership:output_type -> kvcache.controlplane.v1.GetMembershipResponse
	14, // 30: kvcache.controlplane.v1.ControlPlane.SyncMembership:output_type -> kvcache.controlplane.v1.SyncMembershipResponse
	16, // 31: kvcache.controlplane.v1.ControlPlane.RouteBlock:output_type -> kvcache.controlplane.v1.RouteBlockResponse
	18, // 32: kvcache.controlplane.v1.ControlPlane.AnnounceBlock:output_type -> kvcache.controlplane.v1.AnnounceBlockResponse
	20, // 33: kvcache.controlplane.v1.ControlPlane.ForgetBlock:output_type -> kvcache.controlplane.v1.ForgetBlockResponse
	22, // 34: kvcache.controlplane.v1.ControlPlane.GetBlockLocations:output_type -> kvcache.controlplane.v1.GetBlockLocationsResponse
	26, // [26:35] is the sub-list for method output_type
	17, // [17:26] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_control_plane_proto_init() }
func file_control_plane_proto_init() {
	if File_control_plane_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_plane_proto_rawDesc), len(file_control_plane_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_plane_proto_goTypes,
		DependencyIndexes: file_control_plane_proto_depIdxs,
		EnumInfos:         file_control_plane_proto_enumTypes,
		MessageInfos:      file_control_plane_proto_msgTypes,
	}.Build()
	File_control_plane_proto = out.File
	file_control_plane_proto_goTypes = nil
	file_control_plane_proto_depIdxs = nil
}
