// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: control_plane.proto

package controlplane

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlPlane_RegisterNode_FullMethodName      = "/kvcache.controlplane.v1.ControlPlane/RegisterNode"
	ControlPlane_Heartbeat_FullMethodName         = "/kvcache.controlplane.v1.ControlPlane/Heartbeat"
	ControlPlane_LeaveNode_FullMethodName         = "/kvcache.controlplane.v1.ControlPlane/LeaveNode"
	ControlPlane_GetMembership_FullMethodName     = "/kvcache.controlplane.v1.ControlPlane/GetMembership"
	ControlPlane_SyncMembership_FullMethodName    = "/kvcache.controlplane.v1.ControlPlane/SyncMembership"
	ControlPlane_RouteBlock_FullMethodName        = "/kvcache.controlplane.v1.ControlPlane/RouteBlock"
	ControlPlane_AnnounceBlock_FullMethodName     = "/kvcache.controlplane.v1.ControlPlane/AnnounceBlock"
	ControlPlane_ForgetBlock_FullMethodName       = "/kvcache.controlplane.v1.ControlPlane/ForgetBlock"
	ControlPlane_GetBlockLocations_FullMethodName = "/kvcache.controlplane.v1.ControlPlane/GetBlockLocations"
)

// ControlPlaneClient is the client API for ControlPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ControlPlane 只承载集群控制面信息：membership、路由、block 元数据。
// 大块 KV payload 不走 gRPC/protobuf，继续通过 internal/network 的 P2P 流式 TCP 传输。
type ControlPlaneClient interface {
	// RegisterNode 把一个节点加入集群成员表，通常在 daemon 启动时调用。
	RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error)
	// Heartbeat 续约节点存活状态，并返回 coordinator 当前拓扑版本。
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// LeaveNode 逻辑下线节点，控制面应生成 tombstone 压制旧状态包。
	LeaveNode(ctx context.Context, in *LeaveNodeRequest, opts ...grpc.CallOption) (*LeaveNodeResponse, error)
	// GetMembership 拉取当前成员表快照，供新节点启动或拓扑缓存刷新使用。
	GetMembership(ctx context.Context, in *GetMembershipRequest, opts ...grpc.CallOption) (*GetMembershipResponse, error)
	// SyncMembership 向对端推送本地观察到的成员状态，用于 gossip/多 coordinator 同步。
	SyncMembership(ctx context.Context, in *SyncMembershipRequest, opts ...grpc.CallOption) (*SyncMembershipResponse, error)
	// RouteBlock 查询 blockID 对应的 primary 和 fallback 节点。
	RouteBlock(ctx context.Context, in *RouteBlockRequest, opts ...grpc.CallOption) (*RouteBlockResponse, error)
	// AnnounceBlock 上报本节点已经持有某个 block 的元数据。
	AnnounceBlock(ctx context.Context, in *AnnounceBlockRequest, opts ...grpc.CallOption) (*AnnounceBlockResponse, error)
	// ForgetBlock 上报本节点已经删除某个 block，用于控制面清理位置索引。
	ForgetBlock(ctx context.Context, in *ForgetBlockRequest, opts ...grpc.CallOption) (*ForgetBlockResponse, error)
	// GetBlockLocations 查询控制面已知的 block 副本位置。
	GetBlockLocations(ctx context.Context, in *GetBlockLocationsRequest, opts ...grpc.CallOption) (*GetBlockLocationsResponse, error)
}

type controlPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneClient(cc grpc.ClientConnInterface) ControlPlaneClient {
	return &controlPlaneClient{cc}
}

func (c *controlPlaneClient) RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterNodeResponse)
	err := c.cc.Invoke(ctx, ControlPlane_RegisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, ControlPlane_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) LeaveNode(ctx context.Context, in *LeaveNodeRequest, opts ...grpc.CallOption) (*LeaveNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaveNodeResponse)
	err := c.cc.Invoke(ctx, ControlPlane_LeaveNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) GetMembership(ctx context.Context, in *GetMembershipRequest, opts ...grpc.CallOption) (*GetMembershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMembershipResponse)
	err := c.cc.Invoke(ctx, ControlPlane_GetMembership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) SyncMembership(ctx context.Context, in *SyncMembershipRequest, opts ...grpc.CallOption) (*SyncMembershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncMembershipResponse)
	err := c.cc.Invoke(ctx, ControlPlane_SyncMembership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) RouteBlock(ctx context.Context, in *RouteBlockRequest, opts ...grpc.CallOption) (*RouteBlockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteBlockResponse)
	err := c.cc.Invoke(ctx, ControlPlane_RouteBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) AnnounceBlock(ctx context.Context, in *AnnounceBlockRequest, opts ...grpc.CallOption) (*AnnounceBlockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnnounceBlockResponse)
	err := c.cc.Invoke(ctx, ControlPlane_AnnounceBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) ForgetBlock(ctx context.Context, in *ForgetBlockRequest, opts ...grpc.CallOption) (*ForgetBlockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForgetBlockResponse)
	err := c.cc.Invoke(ctx, ControlPlane_ForgetBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) GetBlockLocations(ctx context.Context, in *GetBlockLocationsRequest, opts ...grpc.CallOption) (*GetBlockLocationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlockLocationsResponse)
	err := c.cc.Invoke(ctx, ControlPlane_GetBlockLocations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlPlaneServer is the server API for ControlPlane service.
// All implementations must embed UnimplementedControlPlaneServer
// for forward compatibility.
//
// ControlPlane 只承载集群控制面信息：membership、路由、block 元数据。
// 大块 KV payload 不走 gRPC/protobuf，继续通过 internal/network 的 P2P 流式 TCP 传输。
type ControlPlaneServer interface {
	// RegisterNode 把一个节点加入集群成员表，通常在 daemon 启动时调用。
	RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error)
	// Heartbeat 续约节点存活状态，并返回 coordinator 当前拓扑版本。
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// LeaveNode 逻辑下线节点，控制面应生成 tombstone 压制旧状态包。
	LeaveNode(context.Context, *LeaveNodeRequest) (*LeaveNodeResponse, error)
	// GetMembership 拉取当前成员表快照，供新节点启动或拓扑缓存刷新使用。
	GetMembership(context.Context, *GetMembershipRequest) (*GetMembershipResponse, error)
	// SyncMembership 向对端推送本地观察到的成员状态，用于 gossip/多 coordinator 同步。
	SyncMembership(context.Context, *SyncMembershipRequest) (*SyncMembershipResponse, error)
	// RouteBlock 查询 blockID 对应的 primary 和 fallback 节点。
	RouteBlock(context.Context, *RouteBlockRequest) (*RouteBlockResponse, error)
	// AnnounceBlock 上报本节点已经持有某个 block 的元数据。
	AnnounceBlock(context.Context, *AnnounceBlockRequest) (*AnnounceBlockResponse, error)
	// ForgetBlock 上报本节点已经删除某个 block，用于控制面清理位置索引。
	ForgetBlock(context.Context, *ForgetBlockRequest) (*ForgetBlockResponse, error)
	// GetBlockLocations 查询控制面已知的 block 副本位置。
	GetBlockLocations(context.Context, *GetBlockLocationsRequest) (*GetBlockLocationsResponse, error)
	mustEmbedUnimplementedControlPlaneServer()
}

// UnimplementedControlPlaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlPlaneServer struct{}

func (UnimplementedControlPlaneServer) RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedControlPlaneServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedControlPlaneServer) LeaveNode(context.Context, *LeaveNodeRequest) (*LeaveNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LeaveNode not implemented")
}
func (UnimplementedControlPlaneServer) GetMembership(context.Context, *GetMembershipRequest) (*GetMembershipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMembership not implemented")
}
func (UnimplementedControlPlaneServer) SyncMembership(context.Context, *SyncMembershipRequest) (*SyncMembershipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncMembership not implemented")
}
func (UnimplementedControlPlaneServer) RouteBlock(context.Context, *RouteBlockRequest) (*RouteBlockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RouteBlock not implemented")
}
func (UnimplementedControlPlaneServer) AnnounceBlock(context.Context, *AnnounceBlockRequest) (*AnnounceBlockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnnounceBlock not implemented")
}
func (UnimplementedControlPlaneServer) ForgetBlock(context.Context, *ForgetBlockRequest) (*ForgetBlockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForgetBlock not implemented")
}
func (UnimplementedControlPlaneServer) GetBlockLocations(context.Context, *GetBlockLocationsRequest) (*GetBlockLocationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlockLocations not implemented")
}
func (UnimplementedControlPlaneServer) mustEmbedUnimplementedControlPlaneServer() {}
func (UnimplementedControlPlaneServer) testEmbeddedByValue()                      {}

// UnsafeControlPlaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneServer will
// result in compilation errors.
type UnsafeControlPlaneServer interface {
	mustEmbedUnimplementedControlPlaneServer()
}

func RegisterControlPlaneServer(s grpc.ServiceRegistrar, srv ControlPlaneServer) {
	// If the following call panics, it indicates UnimplementedControlPlaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlPlane_ServiceDesc, srv)
}

func _ControlPlane_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_RegisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).RegisterNode(ctx, req.(*RegisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_LeaveNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).LeaveNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_LeaveNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).LeaveNode(ctx, req.(*LeaveNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_GetMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMembershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).GetMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_GetMembership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).GetMembership(ctx, req.(*GetMembershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_SyncMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncMembershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).SyncMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_SyncMembership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).SyncMembership(ctx, req.(*SyncMembershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_RouteBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).RouteBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_RouteBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).RouteBlock(ctx, req.(*RouteBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_AnnounceBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnnounceBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).AnnounceBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_AnnounceBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).AnnounceBlock(ctx, req.(*AnnounceBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_ForgetBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgetBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).ForgetBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_ForgetBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).ForgetBlock(ctx, req.(*ForgetBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_GetBlockLocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockLocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).GetBlockLocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_GetBlockLocations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).GetBlockLocations(ctx, req.(*GetBlockLocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlPlane_ServiceDesc is the grpc.ServiceDesc for ControlPlane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kvcache.controlplane.v1.ControlPlane",
	HandlerType: (*ControlPlaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNode",
			Handler:    _ControlPlane_RegisterNode_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _ControlPlane_Heartbeat_Handler,
		},
		{
			MethodName: "LeaveNode",
			Handler:    _ControlPlane_LeaveNode_Handler,
		},
		{
			MethodName: "GetMembership",
			Handler:    _ControlPlane_GetMembership_Handler,
		},
		{
			MethodName: "SyncMembership",
			Handler:    _ControlPlane_SyncMembership_Handler,
		},
		{
			MethodName: "RouteBlock",
			Handler:    _ControlPlane_RouteBlock_Handler,
		},
		{
			MethodName: "AnnounceBlock",
			Handler:    _ControlPlane_AnnounceBlock_Handler,
		},
		{
			MethodName: "ForgetBlock",
			Handler:    _ControlPlane_ForgetBlock_Handler,
		},
		{
			MethodName: "GetBlockLocations",
			Handler:    _ControlPlane_GetBlockLocations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "control_plane.proto",
}
